### ISSUE TITLE
Uncaught Error: Minified React error

### ISSUE THREAD

**Issue by rzmk** [shuding/nextra#1409] opened 2023-01-28 04:23 UTC
Hi, I'm getting the following console errors only on the deployed production build of my Nextra sites:

![image](https://user-images.githubusercontent.com/30333942/215241618-9d28719c-3518-4890-9ef2-ebe9b38866aa.png)

Here are the direct error links:

- https://reactjs.org/docs/error-decoder.html?invariant=425
- https://reactjs.org/docs/error-decoder.html?invariant=418
- https://reactjs.org/docs/error-decoder.html?invariant=423

I'm not sure but it seems this happens when working with sub-docs. For example, I got this error when deploying [the sub-docs example project on StackBlitz](https://stackblitz.com/edit/nextra-2-docs-eszspq) that is [referenced on the docs](https://nextra.site/docs/docs-theme/page-configuration#sub-docs:~:text=look%20like%20this%3A-,Live%20example%20on%20StackBlitz%20%E2%86%97,-(opens%20in%20a)).

I uploaded the same sub-docs example project from StackBlitz to [this repository](https://github.com/rzmk/tmp-nextra-test) and [deployed on Vercel here](https://tmp-nextra-test.vercel.app/). When I refresh the page or go to sub-docs pages and refresh I get the errors I've shown above.

Not sure what exactly is causing the errors or how to fix them.

**Comment by B2o5T** [comment] 2023-01-28 16:11
idk how to debug this since locally while running `next dev` or `next build` I was unable to reproduce

**Comment by dimaMachina** [comment] 2024-09-28 12:37
Closing due age

**Closed by dimaMachina** 2024-09-28 12:37 UTC
Labels: bug

**Comment by JimmyAppelt** [comment] 2025-08-22 13:51
@dimaMachina @rzmk 

I'm still getting this with Nextra, and I see it on a lot of Nextra sites, including https://nextra.site/ at the time of writing (only shows in production):

```
Uncaught Error: Minified React error #418; visit https://react.dev/errors/418?args[]=text&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rD (827c5df7-1ae1ebecc19a9289.js:1:35061)
    at rO (827c5df7-1ae1ebecc19a9289.js:1:36094)
    at 827c5df7-1ae1ebecc19a9289.js:1:117790
    at iS (827c5df7-1ae1ebecc19a9289.js:1:122662)
    at ib (827c5df7-1ae1ebecc19a9289.js:1:114450)
    at 827c5df7-1ae1ebecc19a9289.js:1:110437
    at io (827c5df7-1ae1ebecc19a9289.js:1:110538)
    at iY (827c5df7-1ae1ebecc19a9289.js:1:132641)
    at MessagePort.w (6698-5696448d4261e869.js:1:53867)
```

I've read this is most commonly a hydration error somewhere.
