### ISSUE TITLE
Is there a way for sidebar headings to link to the index instead of collapsing the section?

### ISSUE THREAD

**Issue by pbassham** [shuding/nextra#243] opened 2021-11-09 15:01 UTC

**Comment by h0n24** [comment] 2021-12-12 20:02
+1

**Comment by B2o5T** [comment] 2022-08-04 23:49
Duplicate of https://github.com/shuding/nextra/issues/85 (will work on fixing it soon)

**Closed by B2o5T** 2022-08-04 23:49 UTC
Labels: enhancement

**Comment by WooodHead** [comment] 2023-08-22 08:44
Just create a file with same name as folder:

- features.mdx
- features
  - readfile.mdx
  - writefile.mdx

https://turbo.build/pack/docs/features

![image](https://github.com/shuding/nextra/assets/5668806/2ba460d2-308e-4f96-bf46-a4159b3b1479)
