### ISSUE TITLE
Feedback for “Settings Menu”

### ISSUE THREAD

**Issue by lmccook** [shuding/nextra#2710] opened 2024-02-14 18:46 UTC
Hi I am unable to add an image.  It asks for an image URL which I don't have.  It says on the settings menu that I can add a jpeg, png, svg, etc, but I am not able to.  Is there a way I can add this somehow?

Thanks

**Comment by mutasim77** [comment] 2024-02-17 03:53
Next time when asking, please provide what you TRIED and what the ISSUE is.

**Comment by dimaMachina** [comment] 2024-10-07 19:19
closing since it seems you issue is unrelated to Nextra

**Closed by dimaMachina** 2024-10-07 19:19 UTC
