### ISSUE TITLE
Page being "type": "page" and having a sidebar nontheless

### ISSUE THREAD

**Issue by gianlucajahn** [shuding/nextra#1528] opened 2023-02-19 16:46 UTC
I have an index file that is of the "type": "page", meaning it has no sidebar, which is the desired behavior for the index file. 

I have a navbar item ("documentation") that also has the "type": "page" because that is what's necessary to have it on the navbar. 

When the user opens said Documentation by clicking this navbar link, he needs to be able to see the sidebar, though, to be able to navigate the documentation. Setting the "sidebar" to true in the "theme" object in _meta.json for the documentation file does not work.

```
{
  "index": {
    "title": "About",
    "type": "page",
    "display": "hidden"
  },
  "documentation": {
    "title": "Documentation",
    "type": "page",
    "theme": {
      "breadcrumb": true,
      "footer": true,
      "sidebar": true,
      "toc": true,
      "pagination": true
    }
  }
}
```

Any solution to this? This has to be possible, right?

**Comment by C-EO** [comment] 2023-02-19 17:54
@gianlucajahn  Can you provide a link to an example?

**Comment by B2o5T** [comment] 2023-02-20 01:01
Please provide a reproduction

**Comment by B2o5T** [comment] 2023-03-13 23:01
closing due to silence

**Closed by B2o5T** 2023-03-13 23:01 UTC
Labels: reproduction needed
