### ISSUE TITLE
Bug with “*” level page config in V3

### ISSUE THREAD

**Issue by CaryiWong** [shuding/nextra#3576] opened 2024-10-28 09:32 UTC
In this version, the wildcard configuration of the * symbol in the underlying folder will affect the page configuration of the top-level or even all other levels

![image](https://github.com/user-attachments/assets/fb948be8-3579-4a8d-ba54-300033611c4a)

please refer to picture：When I edit _meta.js in folder1 like this, then all my pages will cover by this configuration, even in folder2, It's not good, pls help~

**Comment by dimaMachina** [comment] 2024-10-28 09:35
please create reproduction, so this should be quickly fixed

**Comment by CaryiWong** [comment] 2024-10-28 09:47
OK Tks , waiting for an update~

**Comment by dimaMachina** [comment] 2024-10-28 11:15
Which update? Provide reproduction, I can't reproduce it

**Comment by dimaMachina** [comment] 2024-10-28 11:20
cc @morgan-jarry

**Comment by dimaMachina** [comment] 2024-10-30 09:15
closing, please create a reproduction

**Closed by dimaMachina** 2024-10-30 09:15 UTC
Labels: question, reproduction needed
