### ISSUE TITLE
No syntax hilight for code block

### ISSUE THREAD

**Issue by zhqu1148980644** [shuding/nextra#80] opened 2021-01-02 13:09 UTC
I cloned this repo, run `yarn add .` and then `yarn dev`, code blocks in localhost website does not have highlights.

![image](https://user-images.githubusercontent.com/29366130/103458000-d7470900-4d3e-11eb-8016-38b48e05466a.png)

**Comment by naufaldi** [comment] 2021-01-19 17:24
i trying to clone it, and when in `npm run dev` code blocks dont have highlights. But, trying upload in vercel / `npm run build` will has highlights, only in production

**Comment by LucaNerlich** [comment] 2021-03-27 12:58
Interesting, Im having the same issuem just the other way around, code highlighting works on localhost (next dev and next start) but as soon as I roll it out on prod, code highlighting does not work anymore.

I am using these prism imports

https://nextra.vercel.app/docs/advanced/code-highlighting

Before code highlighting did not work at all.

**Comment by zhqu1148980644** [comment] 2021-03-27 13:00
@naufaldi

**Comment by LucaNerlich** [comment] 2021-03-27 13:16
ive just tested with deployment on vercel and code highlighting works here, it just looks a bit odd, since nextra uses a dark backround for code / pre blocks, which makes text unreadable.

**Comment by shuding** [comment] 2021-05-19 17:49
Can't reproduce this personally, I think more insights are needed from the community. Will keep eyes open on this!

**Comment by phc5** [comment] 2021-09-23 15:56
When I use `npm install` -> `npm run dev`, syntax highlighting does not work. 

If I use `yarn`, then it works.

**Comment by spaceinvadev** [comment] 2021-11-20 17:16
I'm having this issue as well. I'm trying to enable syntax highlighting for Swift. I followed the instructions and added the needed config to the `_app.js` file yet syntax highlighting does not work. Nor for Javascript code snippets.

Here's my `_app.js` file:
```js
import Prism from 'prism-react-renderer/prism'
;(typeof global !== 'undefined' ? global : window).Prism = Prism

require('prismjs/components/prism-swift')

import 'nextra-theme-docs/style.css'
import '../styles/globals.css'

export default function Nextra({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```

This is what gets rendered:
<img width="1149" alt="Screen Shot 2021-11-20 at 12 15 32 PM" src="https://user-images.githubusercontent.com/49292621/142735263-db0ab180-e6b6-4cfb-a563-b2c26cdb8cd6.png">

**Comment by suica** [comment] 2022-05-29 10:28
You may try the versions of packages used in https://github.com/shuding/site/blob/master/package.json if you cannot see the code highlighting in blog theme.

**Comment by daltonturner** [comment] 2022-05-29 20:41
> You may try the versions of packages used in https://github.com/shuding/site/blob/master/package.json if you cannot see the code highlighting in blog theme.

This worked for me! Thank you, @suica!

**Comment by B2o5T** [comment] 2022-08-20 14:40
closing since works fine in beta 2

**Closed by B2o5T** 2022-08-20 14:40 UTC
Labels: help wanted
