### ISSUE TITLE
Missing styles after starting the dev mode following the guide installation

### ISSUE THREAD

**Issue by easychen** [shuding/nextra#3461] opened 2024-10-15 16:08 UTC
**Describe the bug**

After following the guide to install, running `npm run dev` results in the following:

**To Reproduce** Steps to reproduce the behavior:

1. Create a new directory and run `npm init -y`
2. Install the necessary packages: `npm i next react react-dom nextra nextra-theme-docs`
3. Create `next.config.mjs`
4. Create `theme.config.jsx`
5. Create `pages/index.mdx`
6. Run `npm run dev`

<img width="1836" alt="image" src="https://github.com/user-attachments/assets/469a8577-552f-4604-bd2a-74d3eef3cda5">

**Expected behavior**  
The initial page should load with styles.

**Screenshots**  
![image](https://github.com/user-attachments/assets/53e5084a-0aa3-4a7b-9253-adb65faabd08)

**Desktop :**

- OS: Mac
- Browser: Edge
- Version: 129.0.2792.89

**Additional Notes**
Running npm run build && npm run start works as expected.

**Comment by easychen** [comment] 2024-10-15 16:09
package.json:

{
  "name": "doc",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^14.2.15",
    "nextra": "^3.0.12",
    "nextra-theme-docs": "^3.0.12",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }
}

**Comment by dimaMachina** [comment] 2024-10-15 16:37
Without providing runnable reproduction, I am unable to help

**Comment by easychen** [comment] 2024-10-15 16:45
[demo.zip](https://github.com/user-attachments/files/17381889/demo.zip)

I've zipped up the code, can you check if it reproduces?

**Comment by dimaMachina** [comment] 2024-10-15 16:47
please create GitHub repo, I will not download untrusted .zip files

**Comment by 87xie** [comment] 2024-10-15 16:47
Adding a `page/_app.jsx` file may temporarily resolve this issue.

```jsx
function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default App
```

**Comment by easychen** [comment] 2024-10-15 23:58
> Adding a `pages/_app.jsx` file may temporarily resolve this issue.
> 
> ```js
> function App({ Component, pageProps }) {
>   return <Component {...pageProps} />
> }
> 
> export default App
> ```

Thank you, it works. Maybe this step should be added to the guide?

**Comment by dimaMachina** [comment] 2024-10-16 00:50
just create a github reproduction and I could fix it

**Comment by dimaMachina** [comment] 2024-10-16 00:55
I will close this issue since it's a duplicate of https://github.com/shuding/nextra/issues/3357, feel free to share a reproduction and this issue could be fixed

**Closed by dimaMachina** 2024-10-16 00:55 UTC
Labels: bug
