### ISSUE TITLE
Old Sidebar is shown in the page until the page is updated manually - feedback for the team

### ISSUE THREAD

**Issue by agratapatel** [shuding/nextra#1806] opened 2023-04-29 08:29 UTC
While building a nextra doc, I noticed that the sidebar of a specific page only gets updated when I update any contents on the page. So the homepage will keep showing the older sidebar until a content - even a single letter is updated on the home page. How do we keep the sidebar updated with the newest _meta.json pages without updating existing pages every single time?

**Comment by abhaytalreja** [comment] 2023-04-29 18:24
@agratapatel - Are you talking about local? or is your app deployed somewhere?

This seems to be a caching issue.

**Comment by mikaalnaik** [comment] 2023-05-03 14:55
I'm experiencing this as well. The footer `<- Previous Page` and `Next Page ->` lead to 404, and the sidebar points to the old url as well leading to a 404. 

I can navigate to the page directly by URL, but can sort out why that's being cached.

**Comment by agratapatel** [comment] 2023-05-03 14:58
@abhaytalreja it's deployed here: https://land-a-design-job-book.vercel.app/

I have fixed it for now through a hack by updating the page every time - but the issue still persists.

**Comment by mikaalnaik** [comment] 2023-05-03 15:24
> @abhaytalreja it's deployed here: https://land-a-design-job-book.vercel.app/
> 
> I have fixed it for now through a hack by updating the page every time - but the issue still persists.

@abhaytalreja is the code OS? Would love to see how you got around this.

**Comment by StubbornDeer** [comment] 2023-05-23 19:14
Not working for me. I had to rename the title of the dropdown on the left menu and there is NO any page associated with this item. Tried to update the pages of upper and lower levels, no result. I think it's very confusing and can be considered as a bug. At least, the devs could give a clue which cache should be cleaned to make it work.

**Comment by bryandandan** [comment] 2023-05-30 14:27
Did you find a fix for this? i see the old sidebar too from time to time

**Comment by B2o5T** [comment] 2023-05-30 14:28
@bryandandan https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595

**Comment by StubbornDeer** [comment] 2023-05-30 22:56
> Did you find a fix for this? i see the old sidebar too from time to time

Eventually, somebody gave me a piece of advice that worked: when I need the sidebar to be updated, I do the manual redeploy on Vercel. When doing so, it asks if you want to use the cache and I say no:
![image](https://github.com/shuding/nextra/assets/91156314/cc5a3858-005c-45f1-900b-82c77d1d403b)

**Comment by kevinlu1248** [comment] 2023-07-12 04:44
Same for me this fixed it for me!

**Comment by holic** [comment] 2023-08-07 13:47
I think this is a dupe of https://github.com/shuding/nextra/issues/1342 ?

**Comment by iamhectorsosa** [comment] 2023-09-13 10:08
This is the same issue we're experiencing in our projects. It is already reported. Tagging to follow up.

@ericvalcik @jakubschenk

**Comment by ddryo** [comment] 2023-10-09 06:12
I encountered the same problem and was very distressed.

I was able to solve it by manually redeploying with "Use existing Build Cache" unchecked, as commented here.

Thank you very much.

**Comment by B2o5T** [comment] 2023-10-12 13:25
closing as duplicate https://github.com/shuding/nextra/issues/1564#issuecomment-1447419595

**Closed by B2o5T** 2023-10-12 13:25 UTC
Labels: duplicate
