### ISSUE TITLE
Unable to start configured as custom theme

### ISSUE THREAD

**Issue by cangSDARM** [shuding/nextra#1484] opened 2023-02-08 07:38 UTC
![image](https://user-images.githubusercontent.com/20441896/217464305-e85af4b5-fd27-4e0f-b75e-8cb0599f409f.png)

Change to nextra-theme-docs works fine.

Hierarchy:
![image](https://user-images.githubusercontent.com/20441896/217463944-09b7a5bc-cc16-48c0-81b1-791bd969811e.png)

next.config.mjs:
```js
import nextra from "nextra";

const withNextra = nextra({
  theme: "./theme.tsx",
  staticImage: true,
});

export default withNextra({
  reactStrictMode: true,
  // Other Next.js configurations
});
```

command `pnpm next`

**Comment by B2o5T** [comment] 2023-02-08 12:16
please provide reproduction repo

**Comment by B2o5T** [comment] 2023-03-13 23:01
closing due to silence

**Closed by B2o5T** 2023-03-13 23:01 UTC
Labels: reproduction needed
