### ISSUE TITLE
[BUG] TOC highlights the wrong section when current section is exiting the viewport

### ISSUE THREAD

**Issue by lakshya0246** [shuding/nextra#2020] opened 2023-06-28 18:59 UTC
### Description
There's an issue in the Table of contents (TOC) on the right. If you click on a link in the toc, and scroll beyond the section, as you scroll, the TOC jumps to and highlights a link that is not in view, then comes back to the correctly highlighted link.

### Reproduction
The issue can be observed on this page:
https://nextra.site/docs/docs-theme/theme-configuration

1. Click on the link `MDX Components` in the TOC under `Content`
2. The page scrolls to `MDX Components`. ✅
3. But `Global` is still highlighted in the TOC. ❌
5. Now scroll the page slowly up until `MDX Components` is about to exit the viewport from bottom. TOC jumps to `Global`.  ❌

Tested on: 
- Chrome 114.0.5735.198
- MacBook Pro 16
- Viewport sizes : 976 x 1920 and 1000 x 1666

**Comment by B2o5T** [comment] 2023-08-23 17:18
please attach video, can't reproduce

**Comment by lakshya0246** [comment] 2023-08-25 21:02
Sure, here's the video

**Comment by B2o5T** [comment] 2023-08-25 21:19
Thank you! Will debug why this occurs

**Comment by dimaMachina** [comment] 2024-09-15 17:10
should be fixed by https://github.com/shuding/nextra/pull/3249

**Closed by dimaMachina** 2024-09-15 17:10 UTC
Labels: bug, help wanted
