### ISSUE TITLE
If the mdx file name is in Chinese, then it will report an error 404.

### ISSUE THREAD

**Issue by subutay** [shuding/nextra#307] opened 2021-12-30 08:22 UTC
I like this generator very much, but it has some problems. It cannot use mdx files with Chinese names, such as: 入门.mdx.
On the front end, "入门" can be displayed normally in the sidebar. But after clicking, a 404 error will appear.
Is there a solution?

**Comment by shuding** [comment] 2022-01-02 13:31
Duplicate of #97.

**Closed by shuding** 2022-01-02 13:31 UTC
