### ISSUE TITLE
HookWebpackError when yarn build

### ISSUE THREAD

**Issue by stephzero1** [shuding/nextra#1324] opened 2023-01-20 10:34 UTC
I got this error when i run: `yarn build` with the latest version of nextra:
```
  "dependencies": {
    "next": "^13.1.3",
    "nextra": "^2.2.9",
    "nextra-theme-docs": "^2.2.9",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "eslint": "^8.31.0",
    "eslint-config-next": "^13.1.3",
    "eslint-config-prettier": "^8.5.0"
  }
```
Any hint?

**Comment by B2o5T** [comment] 2023-01-20 20:19
please provide reproduction repo

**Comment by stephzero1** [comment] 2023-01-23 15:48
Sorry, the problem was the uppercase extension on some images.
ex:
IMAGE: /public/image.PNG
MDX: ....![](/image.PNG)

And the buld stage was failing not finding some-strange-hash.PNG

With nextra 2.0.2, build worked fine, but with the newer version there is a problem.
I think the bug is how nextra/next handle the uppercase extension on Windows, but i haven't enough time to check.

Solution: rename all file and the mdx reference in lowercase.

**Comment by B2o5T** [comment] 2023-01-23 16:50
Thanks for your answer ❤️

**Comment by B2o5T** [comment] 2023-01-23 17:33
I reopened this issue because I think we can fix it to ignore extension case

**Comment by B2o5T** [comment] 2023-01-24 07:46
seems this error goes not from nextra but from `@vercel/nft`, so I'll close it 🫠

<img width="708" alt="image" src="https://user-images.githubusercontent.com/7361780/214237369-5e80319f-f5f3-4f5c-a3d4-50cad3dabc33.png">

**Closed by B2o5T** 2023-01-24 07:46 UTC
Labels: bug
