### ISSUE TITLE
Idea: add `back to top` button

### ISSUE THREAD

**Issue by kaitoukid-1412** [shuding/nextra#1764] opened 2023-04-17 02:32 UTC

**Comment by abhaytalreja** [comment] 2023-04-17 04:07
You can actually implement it yourself, you don't need it to be in the framework. May be we can add it to the theme.

Here is how I implemented on my site - https://teachingagile.com/

In your `theme.config.tsx` file, add the below code. 
```js
const config: DocsThemeConfig = {
  ...
  main: ({ children }) => {
    return (
      <div className="nx-my-8">
        {children}
        <BackToTop />
      </div>
    )
  },
}
```

Create your own `BackToTop` component

```js
import React, { useState } from 'react'

type Props = {}

export default function BackToTop({}: Props) {
  const isBrowser = () => typeof window !== 'undefined' //The approach recommended by Next.js
  const [visible, setVisible] = useState(false)

  const scrollToTop = () => {
    if (!isBrowser()) return
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  const toggleVisible = () => {
    const scrolled = document.documentElement.scrollTop
    if (scrolled > 300) {
      setVisible(true)
    } else if (scrolled <= 300) {
      setVisible(false)
    }
  }
  if (isBrowser()) {
    window.addEventListener('scroll', toggleVisible)
  }

  return (
    <button
      className="nx-fixed nx-bottom-0 ltr:nx-right-3 w-full nx-mb-4 nx-bg-gray-200 nx-p-2 nx-rounded-xl hover:nx-bg-gray-100"
      onClick={scrollToTop}
      style={{ display: visible ? 'inline' : 'none' }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        className="nx-w-8 nx-h-8 nx-rounded-lg nx-bg-gray-200 nx-text-center nx-flex nx-justify-center hover:nx-bg-gray-100"
        width={24}
        height={24}
        viewBox="0 0 24 24"
        strokeWidth="2"
        stroke="currentColor"
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
      >
        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
        <path d="M12 5l0 14"></path>
        <path d="M18 11l-6 -6"></path>
        <path d="M6 11l6 -6"></path>
      </svg>
    </button>
  )
}
```

You can directly use this code and try. It should look just as it looks on my website.

I hope it helps.

**Comment by C-EO** [comment] 2023-04-17 09:29
@B2o5T This is a duplicate of #1061. 
@shenlong616 But feel free to implement one to add to the codebase. @abhaytalreja Your example is good. I could try to implement and add it to the codebase myself and create a PR.

**Closed as completed** 2023-04-19 07:50 UTC
