### ISSUE TITLE
Vercel caching issue

### ISSUE THREAD

**Issue by imranbarbhuiya** [shuding/nextra#1564] opened 2023-02-27 09:39 UTC
Hi, our site https://guide.sofi.gg is hosted on vercel and recently, it started to give this error
```sh

@sofi/guide:build: info  - Creating an optimized production build...
--
15:03:59.797 | @sofi/guide:build: <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /vercel/path0/node_modules/nextra/dist/plugin.mjs for build dependencies failed at 'import(filePath)'.
15:03:59.797 | @sofi/guide:build: <w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
15:03:59.811 | @sofi/guide:build: <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve './__temp__' in '/vercel/path0/node_modules/nextra/dist'
15:03:59.811 | @sofi/guide:build: <w> while resolving './__temp__' in /vercel/path0/node_modules/nextra/dist as file
15:03:59.811 | @sofi/guide:build: <w>  at resolve esm file ./__temp__
15:03:59.811 | @sofi/guide:build: <w>  at file dependencies /vercel/path0/node_modules/nextra/dist/compile.mjs
15:03:59.811 | @sofi/guide:build: <w>  at file /vercel/path0/node_modules/nextra/dist/compile.mjs
15:03:59.811 | @sofi/guide:build: <w>  at resolve esm file ./compile.mjs
15:03:59.811 | @sofi/guide:build: <w>  at file dependencies /vercel/path0/node_modules/nextra/dist/loader.mjs
15:03:59.812 | @sofi/guide:build: <w>  at file /vercel/path0/node_modules/nextra/dist/loader.mjs
15:03:59.812 | @sofi/guide:build: <w>  at resolve esm file ./dist/loader.mjs
15:03:59.812 | @sofi/guide:build: <w>  at file dependencies /vercel/path0/node_modules/nextra/loader.js
15:03:59.812 | @sofi/guide:build: <w>  at file /vercel/path0/node_modules/nextra/loader.js
15:03:59.812 | @sofi/guide:build: <w>  at resolve commonjs /vercel/path0/node_modules/nextra/loader.js
15:04:00.650 | @sofi/guide:build: <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /vercel/path0/node_modules/nextra/dist/plugin.mjs for build dependencies failed at 'import(filePath)'.
15:04:00.651 | @sofi/guide:build: <w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
15:04:00.657 | @sofi/guide:build: <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve './__temp__' in '/vercel/path0/node_modules/nextra/dist'
15:04:00.658 | @sofi/guide:build: <w> while resolving './__temp__' in /vercel/path0/node_modules/nextra/dist as file
15:04:00.658 | @sofi/guide:build: <w>  at resolve esm file ./__temp__
15:04:00.658 | @sofi/guide:build: <w>  at file dependencies /vercel/path0/node_modules/nextra/dist/compile.mjs
15:04:00.658 | @sofi/guide:build: <w>  at file /vercel/path0/node_modules/nextra/dist/compile.mjs
15:04:00.658 | @sofi/guide:build: <w>  at resolve esm file ./compile.mjs
15:04:00.659 | @sofi/guide:build: <w>  at file dependencies /vercel/path0/node_modules/nextra/dist/loader.mjs
15:04:00.659 | @sofi/guide:build: <w>  at file /vercel/path0/node_modules/nextra/dist/loader.mjs
15:04:00.659 | @sofi/guide:build: <w>  at resolve esm file ./dist/loader.mjs
15:04:00.659 | @sofi/guide:build: <w>  at file dependencies /vercel/path0/node_modules/nextra/loader.js
15:04:00.659 | @sofi/guide:build: <w>  at file /vercel/path0/node_modules/nextra/loader.js
15:04:00.659 | @sofi/guide:build: <w>  at resolve commonjs /vercel/path0/node_modules/nextra/loader.js
```

Because of this, when going to the homepage, it doesn't show the `events` tab but if u go to https://guide.sofi.gg/events, it shows the page and tab too.

I'm using
```json
		"next": "^13.2.1",
		"nextra": "^2.2.16",
		"nextra-theme-docs": "^2.2.16",
```
with `type: module`

I'm also using `_app.mdx` instead of tsx

**Comment by C-EO** [comment] 2023-02-27 18:13
Same issue
@B2o5T What's the cause? It seems to be a problem of mainly v2.2.16

**Comment by B2o5T** [comment] 2023-02-27 18:49
Please provide a reproduction

**Comment by imranbarbhuiya** [comment] 2023-02-28 01:01
My local builds are working fine. How can I ignore vercel cache?

Also for reproduction, my repo is a monorepo under an org where I can't give access but if I get time, I'll try to make a new repo to reproduce this issue

**Comment by robbear** [comment] 2023-02-28 01:20
> disabling caching worked

That's what I suspected. Vercel's build cache has been a problem for our deployments, too, with problems ranging from build failures as you've observed, to changes in `_meta.json` files not being reflected at runtime. If you haven't discovered it, you might find the Vercel project environment variable, `VERCEL_FORCE_NO_BUILD_CACHE=1`, useful. https://github.com/vercel/vercel/discussions/8057

**Comment by AntoineYANG** [comment] 2023-03-08 12:16
Same issue.
I found some unexpected problems when debugging, about the global state `NEXTRA_INTERNAL`.
There were 32 items (MDX pages) and I then appended one. Everything works well in the development env. However when I inspect the deployment, the route of the new page is accessible but I can't find it in the navbar or in the list. Then I logged the `NEXTRA_INTERNAL` context and found that
* `context` contains all the pages as expected
* `pageMap` contains only the pages deployed before
Actually I consider that `pageMap` is necessary for creating the list, so I guess something about it is working bad.

**Comment by transitive-bullshit** [comment] 2023-03-12 17:59
Same issue which repros for me locally via `next dev`.

If I use latest `next` `13.2.4`, I get this error.

If I downgrade to `next` `13.0.6` (the version of next.js currently used by https://github.com/shuding/nextra-docs-template), then I don't get this error.

If I try `13.2.0`, I don't get the error. So something must've changed in `next.js` between `13.2.0` and `13.2.4` that's causing this.

**Comment by joshmanders** [comment] 2023-03-21 15:08
Getting the same issue locally as @transitive-bullshit.

`next@13.1.6`
`nextra@2.2.14`
`nextra-theme-docs@2.2.14`

**Comment by danez** [comment] 2023-03-24 16:31
Same issue here locally with

nextra 2.2.20
nextra-theme-docs 2.2.20
next 13.2.4

**Comment by steida** [comment] 2023-03-29 13:45
Isn't this related?

https://github.com/vercel/turbo/blob/main/examples/basic/turbo.json#L6

**Comment by ovflowd** [comment] 2023-04-19 18:22
Hey @shuding, any updates here? We're also getting the same...

![image](https://user-images.githubusercontent.com/12037269/233165758-470386cd-0227-4526-9235-700c2a1caa75.png)

**Comment by rtorcato** [comment] 2023-08-22 15:42
only thing that works for me is to delete the .next directory before running next dev

here is my npm script:

`"dev": "rm -rf .next && next dev --port 3001",`

**Comment by davidfurlong** [comment] 2023-12-08 15:40
+1 seeing this

**Comment by dimaMachina** [comment] 2024-10-13 18:54
can someone report if you have similar issues with Nextra 3? Closing for now

**Closed by dimaMachina** 2024-10-13 18:54 UTC
