### ISSUE TITLE
Upgrading from 2.3.0 → 2.4.0 breaks build due to updated path joining

### ISSUE THREAD

**Issue by terrymun** [shuding/nextra#1762] opened 2023-04-16 18:00 UTC
I noticed that after upgrading from Nextra@2.3.0 → Nextra@2.4.0, attempts to build or export my Nextra docs site will fail. The way I use Nextra is not very well documented, as it actually lives as a package in a Nx-managed monorepo, in the folder `packages/docs`, for example.

Attempting to run the build / export command now will cause webpack to throw an error:

```text
./pages/my-page.mdx
Error: ENOENT: no such file or directory, open '[monorepo_root]/packages/docs/packages/docs/pages/my-page.mdx'
```

From the error message above, you can see that attempts to access `my-page.mdx` has failed because the subpath `packages/docs` (the package root in my monorepo) has been duplicated in the path:

```text
'[monorepo_root]/packages/docs/packages/docs/pages/my-page.mdx'
                 ^^^^^^^^^^^^^ ^^^^^^^^^^^^^
                               (duplication)
```

This error does not show up when I downgrade to Nextra@2.3.0.

For a little context, this is how my `next.config.mjs` looks like:

```mjs
import nextra from 'nextra';

const withNextra = nextra({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
});

/**
 * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  images: {
    unoptimized: true,
  },
  experimental: {
    // NOTE: This includes files from the monorepo base
    externalDir: true,
  },
};

export default withNextra(nextConfig);
```

I am no sleuth, but I suspect this might be due to how Nextra reads relative file paths with logic that is slightly tweaked in 2.4.0: [changelog](https://github.com/shuding/nextra/compare/nextra-theme-docs%402.3.0...nextra%402.4.0#diff-b80cbbc7df15b07dd7dadbe8fdf2427e2741c1b9ba8fa65daf3841acb5b41632), namely in `packages/nextra/src/plugin.ts`

**Comment by B2o5T** [comment] 2023-04-22 07:51
Idk why it occurs only for you, pr with fix welcome

**Comment by simoneldevig** [comment] 2023-05-09 07:02
@B2o5T I have a similar issue and created a reproduction at https://github.com/simoneldevig/nextra-nx-repro 

Run `yarn` and `yarn serve:docs` to see the issue.

Getting a `Error: ENOENT: no such file or directory, open '/Users/johndoe/nextra-nx-repro/apps/nextra/apps/nextra/pages/index.mdx'`

I've narrowed it down to be an issue with the change in the `loader.ts` https://github.com/shuding/nextra/compare/nextra-theme-docs%402.3.0...nextra%402.4.0#diff-6be4179817c6ac6a17966d1e43930d6d1f2de7eda6f845cb0fd888feb6a0885fL100-L101

If I change it back to `const mdxPath = context.resourcePath as MdxPath` it works as expected. 

The issue is that both `context.rootContext` and `context._module.resourceResolveData.relativePath` includes `apps/nextra` in their path

**Comment by B2o5T** [comment] 2023-05-09 10:06
@simoneldevig thanks for the investigation, it's very helpful, fix will be released very soon!

**Closed** 2023-05-09 10:44 UTC
Labels: bug
