### ISSUE TITLE
How to configure basePath in Nextra

### ISSUE THREAD

**Issue by YikSanChan** [shuding/nextra#137] opened 2021-04-20 12:55 UTC
Hi,

I am using nextra-theme-docs. After I deploy the app on GitLab CI, my GitLab pages are live,

![image](https://user-images.githubusercontent.com/17229109/115398784-162f9a80-a21a-11eb-979c-3097a2b0c97f.png)

however, as you can see, assets loading fails.

![image](https://user-images.githubusercontent.com/17229109/115398676-fdbf8000-a219-11eb-84ea-76eb8c98e52f.png)

This is because my site is live on http://aiinfra.book.pri.ibanyu.com/docs/, however it tries to load assets from http://aiinfra.book.pri.ibanyu.com/_next/static/chunks/main-b8578ac1074c64daef74.js. This is not working, while http://aiinfra.book.pri.ibanyu.com/docs/_next/static/chunks/main-b8578ac1074c64daef74.js exist. (Note the latter has a `/docs` inside)

I wonder how to configure my nextra app so that my app loads asset from http://aiinfra.book.pri.ibanyu.com/docs/_next/ rather than http://aiinfra.book.pri.ibanyu.com/_next/.

I have tried to edit my theme.config.js to update `path: "/"` to `path: "/docs"`, and also add `basePath: "/docs"` (according to [nextjs docs](https://nextjs.org/docs/api-reference/next.config.js/basepath)), however neither helps.

Any help? Thanks!

**Comment by YikSanChan** [comment] 2021-04-20 12:58
Ah i figure out why, I should add `basePath: "/docs"` to next.config.js rather than theme.config.js.

@shuding Is this a good practice?

**Comment by varunharidas** [comment] 2022-01-28 06:28
Same issue not working for me, this is the config, throws 404

```
const withNextra = require('nextra')('nextra-theme-blog', './theme.config.js')
module.exports = withNextra()
module.exports = {
  basePath: '/docs',
}
```

**Comment by thtmnisamnstr** [comment] 2022-02-06 14:07
@varunharidas You should only have one `module.exports` below:
> ```
> const withNextra = require('nextra')('nextra-theme-blog', './theme.config.js')
> module.exports = withNextra()
> module.exports = {
>   basePath: '/docs',
> }
> ```

Instead, it should be:
```
const withNextra = require('nextra')({
    theme: 'nextra-theme-blog',
    themeConfig: './theme.config.js',
    // optional: add `unstable_staticImage: true` to enable Nextra's auto image import
})
module.exports = withNextra({
    basePath: '/docs',
})
```

You can check out the [rtdl-docs repo](https://github.com/realtimedatalake/rtdl-docs) and the associated [GitHub Pages site](https://realtimedatalake.github.io/rtdl-docs/) for a working example.

**Comment by B2o5T** [comment] 2022-08-20 14:32
closing since `basePath` works, if anyone has a similar problem, I'll reopen the issue

**Closed by B2o5T** 2022-08-20 14:32 UTC

**Comment by raproid** [comment] 2022-08-30 17:15
@B2o5T what about broken paths in search results when I add basePath: '/docs',?
The search results now have doubled the docs part of the path: localhost:3000/docs/docs/app-chain/components/app-chain-testnet-faucet

**Comment by B2o5T** [comment] 2022-08-30 17:22
@raproid do you use latest beta?

**Comment by raproid** [comment] 2022-08-30 18:41
@B2o5T no, I'm using 
    "next": "^12.2.0",
    "nextra": "^2.0.0-beta.6",
    "nextra-theme-docs": "^2.0.0-beta.6",

**Comment by raproid** [comment] 2022-08-30 18:42
So, it's the beta 6.

**Comment by B2o5T** [comment] 2022-08-30 18:56
Try to use beta 21

**Comment by raproid** [comment] 2022-08-30 20:40
Getting 
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/22454517/187538820-53b77894-4fd2-42ea-9a57-ededcbca3ded.png">
when using beta 21

**Comment by raproid** [comment] 2022-08-30 20:40
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/22454517/187538901-50298565-3b04-4e24-8091-dc2d1c6c6ace.png">

getting this when using beta 21

**Comment by raproid** [comment] 2022-08-30 20:40
How to import and declare callouts correctly in beta 21?

**Comment by B2o5T** [comment] 2022-08-30 21:11
import { Callout } from ‘nextra-theme-docs’

**Comment by raproid** [comment] 2022-08-30 22:05
worked it out, thx

How to fix the position of the theme switcher? 
<img width="245" alt="image" src="https://user-images.githubusercontent.com/22454517/187551950-fb1e3604-6a2c-4d67-9526-b1359537f8bf.png">

**Comment by raproid** [comment] 2022-08-30 22:16
and if there's not .md/.mdx file within a section but another section instead I'm getting 404.
e.g. if I click on Affiliated Chains I'm getting 404 as there's only a folder within this folder, no .md/.mdx file to generate a page from.
<img width="239" alt="image" src="https://user-images.githubusercontent.com/22454517/187553229-ff26284c-69ae-4264-b8a9-10cc6d4a0a9a.png">

**Comment by raproid** [comment] 2022-08-30 22:58
Is the search index built locally?
Testing it on localhost, I'm typing a word that sure is in many files in many subfolders under `pages` yet I see no search result for it at all.
What search engine does Nextra use by default? And how is the index built?

**Comment by B2o5T** [comment] 2022-08-31 01:17
> Is the search index built locally?

Try to `next build` and `next start`, in dev env there are some limitations

**Comment by raproid** [comment] 2022-08-31 09:16
@B2o5T what about this bug? https://github.com/shuding/nextra/issues/137#issuecomment-1232224587

**Comment by B2o5T** [comment] 2022-08-31 09:23
Can you show a reproduction repo with this issue

**Comment by raproid** [comment] 2022-08-31 15:56
Of course. 
https://github.com/raproid/raproid.github.io/tree/stage

yarn then yarn next

**Comment by raproid** [comment] 2022-08-31 15:57
And then try to go App Chains > Affiliated Chains

**Comment by raproid** [comment] 2022-08-31 19:23
Also, what tab tag is to use in beta 21?

<Nextra.Tabs> give me "Error: Expected object `Nextra` to be defined: you likely forgot to import, pass, or provide it." error.

**Comment by B2o5T** [comment] 2022-09-01 13:53
Hi @raproid, will take a look at near days

**Comment by raproid** [comment] 2022-09-05 13:52
@B2o5T any news about 
1. The <Nextra.Tabs> tag in latest betas?
2. [The bug](https://github.com/shuding/nextra/issues/137#issuecomment-1232224587)? You can see it live on https://raproid-github-io.vercel.app/ and the direct link is https://raproid-github-io.vercel.app/app-chain/affiliated-chain/bnb-sidechain/

**Comment by B2o5T** [comment] 2022-09-05 20:24
for the 1st - you should use `import { Tabs, Tab } from 'nextra-theme-docs'`
for 2nd I didn't take a look yet

**Comment by raproid** [comment] 2022-09-06 16:54
@B2o5T would be really nice if you could. That's a major bug for Nextra.
Beta 24 is very good. Thank you for your work!

**Comment by B2o5T** [comment] 2022-09-06 19:07
@raproid I can confirm the existing issue on the current beta, but on the not released version of nextra it works fine, so wait little bit, it will be fixed on next beta

PR that fixes your issue https://github.com/shuding/nextra/pull/811

**Comment by NasirAbdullahSyed** [comment] 2023-10-27 06:42
The basePath should not be tied to NextJS's own config, imho.

I currently use Nextra within an existing project SaaS platform, so if I change the basePath, it breaks the entire app's routing.

**Comment by iqbal125** [comment] 2023-11-11 21:56
> The basePath should not be tied to NextJS's own config, imho.
> 
> Theme should have its own basePath.
> 
> I currently use Nextra within an existing project SaaS platform, so if I change the basePath, it breaks the entire app's routing.

Yes I agree, it seems they want nextra to be its own standalone app, but I want to integrate into an existing app where the "/" is already taken.

**Comment by NotDemonix** [comment] 2024-02-01 21:31
Any updates here? I wanna do it too

**Comment by Coderamrin** [comment] 2024-04-21 11:34
> > The basePath should not be tied to NextJS's own config, imho.
> > Theme should have its own basePath.
> > I currently use Nextra within an existing project SaaS platform, so if I change the basePath, it breaks the entire app's routing.
> 
> Yes I agree, it seems they want nextra to be its own standalone app, but I want to integrate into an existing app where the "/" is already taken.

Have you found any solution? 
How to use nextra on an existing next js project under /docs route
