### ISSUE TITLE
Feedback for “Theme Configuration”

### ISSUE THREAD

**Issue by sm1990** [shuding/nextra#3383] opened 2024-10-07 03:07 UTC
Hi All,

I followed your guide and tried to add a TOC to the right sidebar like the image below.
![image](https://github.com/user-attachments/assets/9605e1fb-d059-4f8e-826d-6a80f47398c1)

I updated the `theme.config.js` . But I'm not sure how to add the `toc.float`. Currently the TOC is shown in left sidebar under the page title.

This is my `theme.config.js`
```javascript
import { useTheme } from 'next-themes'

export default {
  logo: () => {
    const { theme } = useTheme()

    return (
      <img 
        src={theme === 'dark' ? '/images/logo/logo-white.svg' : '/images/logo/logo-grey.svg'} 
        alt="Logo" 
        style={{ height: '40px' }} /* Adjust as needed */
      />
    )
  },
  toc:true,
    // other configuration options
}
```
I guess we need to be more clear with the instructions. Maybe I missed something. Hope you can help.

**Comment by oobg** [comment] 2024-10-07 13:56
It is recommended that the `theme.config` file uses either the `.jsx` or `.tsx` extension.

Please review the “Theme Configuration” section of the “Docs Theme” again.
https://nextra.site/docs/docs-theme/theme-configuration#table-of-contents

For the toc sidebar, toc.float is enabled by default.
Setting `toc: true` is not the correct way to configure it.
https://nextra.site/docs/docs-theme/theme-configuration#floating-toc

If additional options are needed, please use the following:

```jsx
toc: {
    float: true,
    backToTop: true,
    title: props => {
        const { frontMatter } = useConfig();
        return frontMatter.title;
    },
    // other toc options...
}
```

Additional question: Have you used heading tags within the `.mdx` file? (For example, using markdown syntax like # or ##.)

If the issue persists even after applying all the changes, please check if the screen width is less than `768px`. At that size, the TOC is merged with the sidebar.

**Comment by dimaMachina** [comment] 2024-10-07 18:58
I think @oobg sent a good answer, thank you a lot!

@sm1990 feel free to reply if something is still unclear, closing for now

**Closed by dimaMachina** 2024-10-07 18:58 UTC

**Comment by sm1990** [comment] 2024-10-08 04:10
@oobg thank you for your solution. There were some issues with the frontmatter in my MD too. Once I fixed them, everything worked 😀

**Comment by oobg** [comment] 2024-10-08 14:04
@sm1990 , I’m glad the issue is resolved. Have a great day! :D
